[package]
name = "embedded-sdmmc"
version = "0.3.0"
authors = ["Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"]
description = "A basic SD/MMC driver for Embedded Rust."
keywords = ["sdcard", "mmc", "embedded", "fat32"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/thejpster/embedded-sdmmc-rs"
edition = "2018"
readme = "README.md"

[dependencies]
embedded-hal = "0.2.3"
byteorder = { version = "1", default-features = false }
log = "0.4"

[dev-dependencies]
hex-literal = "0.3"
env_logger = "0.8"

[features]
# Enables an unstable feature i.e. allows multiple contiguous block-reads of a file via a single read operation.
unstable = []